{{- $componentName := "applinth-marketplace-ui" -}}
---
{{- if (index .Values.global.imageOverrides "applinth-marketplace-ui") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pipes.fullname" (dict "suffix" $componentName "noPrefix" true "root" .) }}
  labels:
{{ include "pipes.labels" . | indent 4 }}
{{ include "pipes.dictSection" (dict "name" "annotations" "items" .Values.global.applinthMarketplaceUI.serviceAnnotations) | indent 2 }}
spec:
  selector:
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: http

{{- end }}
