{{- $componentName := "applinth-marketplace-ui" -}}
---
{{- if (index .Values.global.imageOverrides "applinth-marketplace-ui") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pipes.fullname" (dict "suffix" $componentName "noPrefix" true "root" .) }}
  labels:
{{ include "pipes.labels" . | indent 4 }}
{{ include "pipes.dictSection" (dict "name" "annotations" "items" .Values.global.applinthMarketplaceUI.serviceAnnotations) | indent 2 }}
spec:
  selector:
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 4 }}
  {{- if (eq .Values.global.applinthMarketplaceUI.service.type "NodePort") }}
  type: {{ .Values.global.applinthMarketplaceUI.service.type }}
  {{- end }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      {{- if (and (eq .Values.global.applinthMarketplaceUI.service.type "NodePort") (not (empty .Values.global.applinthMarketplaceUI.service.nodePort))) }}
      nodePort: {{ .Values.global.applinthMarketplaceUI.service.nodePort }}
      {{- end }}

{{- end }}
