{{- $componentName := "detector" -}}
{{- if .Values.global.detector.manageServiceAccount -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pipes.fullname" (dict "suffix" $componentName "root" .) }}
{{ end }}

{{- if .Values.global.detector.manageRBAC -}}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: {{ include "pipes.fullname" (dict "suffix" $componentName "root" .) }}
rules:
- apiGroups: ["", "apps"]
  resources: ["deployments", "pods", "replicasets"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "pipes.fullname" (dict "suffix" $componentName "root" .) }}
subjects:
- kind: ServiceAccount
  name: {{ include "pipes.fullname" (dict "suffix" $componentName "root" .) }}
roleRef:
  kind: Role
  name: {{ include "pipes.fullname" (dict "suffix" $componentName "root" .) }}
  apiGroup: ""
{{- end -}}
