{{- $componentName := "detector" -}}
{{- if .Values.global.monitoring.useInfluxDB -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pipes.fullname" (dict "suffix" $componentName "root" .) }}
  labels:
{{ include "pipes.labels" . | indent 4 }}
spec:
  selector:
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
{{- end -}}
