{{- $componentName := "fluentd" -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pipes.fullname" (dict "suffix" $componentName "root" .) }}
  labels:
{{ include "pipes.labels" . | indent 4 }}
{{ if eq .Values.global.monitoring.logStorage "google" }}
  annotations:
    iam.gke.io/gcp-service-account: "{{ .Values.global.monitoring.googleServiceAccount }}"
{{ end }}
