---
{{- $componentName := "frontend" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pipes.fullname" (dict "suffix" $componentName "noPrefix" true "root" .) }}
  labels:
{{ include "pipes.labels" . | indent 4 }}
{{ include "pipes.dictSection" (dict "name" "annotations" "items" .Values.global.frontend.serviceAnnotations) | indent 2 }}
spec:
  selector:
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 4 }}
  {{- if (ne .Values.global.frontend.service.type "none") }}
  type: {{ .Values.global.frontend.service.type }}
  {{- end }}
  ports:
    - protocol: TCP
      port: {{ .Values.global.frontend.service.port }}
      targetPort: http
      {{- if (and (eq .Values.global.frontend.service.type "NodePort") (not (empty .Values.global.frontend.service.nodePort))) }}
      nodePort: {{ .Values.global.frontend.service.nodePort }}
      {{- end }}
