{{- $componentName := "kapacitor" -}}
{{- if .Values.global.monitoring.useInfluxDB -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pipes.fullname" (dict "suffix" $componentName "noPrefix" true "root" .) }}
  labels:
{{ include "pipes.labels" . | indent 4 }}
spec:
  selector:
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 4 }}
  ports:
    - name: ingest-udp
      protocol: UDP
      port: 9100
      targetPort: ingest-udp
{{- end -}}
