---
{{- $componentName := "limiter" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipes.fullname" (dict "suffix" $componentName "root" .) }}
  labels:
{{ include "pipes.labels" . | indent 4 }}
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 6 }}
  template:
    metadata:
      labels:
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 8 }}
    spec:
{{ include "pipes.imagePullSecrets" . | indent 6 }}
      containers:
        - name: {{ $componentName }}
          image: {{ include "pipes.imageFullname" (dict "image" "limiter" "root" .) }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3333
          env:
            - name: TZ
              value: "{{ .Values.global.timezone }}"
            - name: UDP_LOGGER_URL
              value: {{ include "pipes.fullname" (dict "suffix" "fluentd" "root" .) }}:5120
            - name: LIMITER_ADDR
              value: "0.0.0.0:3333"
            - name: RABBITMQ_DSN
              valueFrom:
                secretKeyRef:
                  key: rabbitmq_dsn
                  name: {{ include "pipes.fullname" (dict "suffix" "secrets" "root" .) }}
            - name: MONGO_DSN
              valueFrom:
                secretKeyRef:
                  key: mongodb_dsn
                  name: {{ include "pipes.fullname" (dict "suffix" "secrets" "root" .) }}
          resources:
{{ toYaml .Values.global.limiter.resources | indent 12 }}

{{- with .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.global.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
