---
{{- $componentName := "repeater" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipes.fullname" (dict "suffix" $componentName "root" .) }}
  labels:
{{ include "pipes.labels" . | indent 4 }}
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 6 }}
  template:
    metadata:
      labels:
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 8 }}
    spec:
{{ include "pipes.imagePullSecrets" . | indent 6 }}
      containers:
        - name: repeater
          image: {{ include "pipes.imageFullname" (dict "image" "repeater" "root" .) }}
          imagePullPolicy: Always
          args: ["./dist/src/bin/pipes.js", "start", "repeater"]
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  key: rabbitmq_host
                  name: {{ include "pipes.fullname" (dict "suffix" "secrets" "root" .) }}
            - name: RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  key: rabbitmq_port
                  name: {{ include "pipes.fullname" (dict "suffix" "secrets" "root" .) }}
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  key: rabbitmq_user
                  name: {{ include "pipes.fullname" (dict "suffix" "secrets" "root" .) }}
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  key: rabbitmq_password
                  name: {{ include "pipes.fullname" (dict "suffix" "secrets" "root" .) }}
            - name: RABBITMQ_VHOST
              valueFrom:
                secretKeyRef:
                  key: rabbitmq_vhost
                  name: {{ include "pipes.fullname" (dict "suffix" "secrets" "root" .) }}
            - name: MONGO_DSN
              valueFrom:
                secretKeyRef:
                  key: mongodb_dsn
                  name: {{ include "pipes.fullname" (dict "suffix" "secrets" "root" .) }}
            - name: REPEATER_CHECK_TIMEOUT
              value: "5000"
          resources:
{{ toYaml .Values.global.repeater.resources | indent 12 }}

{{- with .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.global.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
