{{- $componentName := "topology-api" -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipes.fullname" (dict "suffix" $componentName "root" .) }}
  labels:
{{ include "pipes.labels" . | indent 4 }}
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 6 }}
  template:
    metadata:
      labels:
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 8 }}
    spec:
{{ include "pipes.imagePullSecrets" . | indent 6 }}
      serviceAccountName: {{ include "pipes.fullname" (dict "suffix" $componentName "root" .) }}
      containers:
        - name: topology-api
          image: {{ include "pipes.imageFullname" (dict "image" $componentName "root" .) }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: K8S_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: PLATFORM
              value: k8s
            - name: GENERATOR_PATH
              value: /srv/topology
            - name: MONGO_DSN
              valueFrom:
                secretKeyRef:
                  key: mongodb_dsn
                  name: {{ include "pipes.fullname" (dict "suffix" "secrets" "root" .) }}
            - name: WORKER_DEFAULT_LIMIT_MEMORY
              value: "{{ .Values.global.topologyApi.topologiesResources.defaultLimitMemory }}"
            - name: WORKER_DEFAULT_LIMIT_CPU
              value: "{{ .Values.global.topologyApi.topologiesResources.defaultLimitCpu }}"
            - name: WORKER_DEFAULT_REQUEST_MEMORY
              value: "{{ .Values.global.topologyApi.topologiesResources.defaultRequestMemory }}"
            - name: WORKER_DEFAULT_REQUEST_CPU
              value: "{{ .Values.global.topologyApi.topologiesResources.defaultRequestCpu }}"
            - name: STARTING_POINT_DSN
              value: "{{ .Values.global.starting_point_url }}"
{{- range $name, $def := .Values.global.topologyApi.topologiesExtraEnv }}
            - name: APP_PASS_{{ $name }}
              {{- $def | toYaml | nindent 14}}
{{- end }}
{{- with .Values.global.topologyApi.topologiesExtraSpec }}
            - name: BRIDGE_PODS_ADDITIONAL_SPEC
              value: /config-volume/topologies-extra-spec.yaml
{{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /config-volume
          resources:
{{ toYaml .Values.global.topologyApi.resources | indent 12 }}

      volumes:
        - name: config-volume
          configMap:
            name: {{ include "pipes.fullname" (dict "suffix" $componentName "root" .) }}

{{- with .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.global.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
