{{- $componentName := "topology-api" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pipes.fullname" (dict "suffix" $componentName "root" .) }}
  labels:
{{ include "pipes.labels" . | indent 4 }}
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 4 }}
data:
  topologies-extra-spec.yaml: |
{{ toYaml .Values.global.topologyApi.topologiesExtraSpec | indent 4 }}
