{{- $componentName := "worker" -}}
---
{{- if not .Values.global.imageOverrides.nodejssdk }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipes.fullname" (dict "suffix" $componentName "root" .) }}
  labels:
{{ include "pipes.labels" . | indent 4 }}
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 6 }}
  template:
    metadata:
      labels:
        timestamp: "{{ now | date "20060102150405" }}"
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 8 }}
    spec:
{{ include "pipes.imagePullSecrets" . | indent 6 }}
      containers:
        - name: php-w-nginx
          image: {{ include "pipes.imageFullname" (dict "image" "php-sdk" "root" .) }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          env:
{{ include "pipes.monolithEnv" . | indent 12 }}
{{- range $name, $def := .Values.global.phpSdk.extraEnv }}
            - name: {{ $name }}
              {{- $def | toYaml | nindent 14}}
{{- end }}
            - name: CRYPT_SECRET
              valueFrom:
                secretKeyRef:
                  key: crypt_secret
                  name: {{ include "pipes.fullname" (dict "suffix" "secrets" "root" .) }}
          resources:
{{ toYaml .Values.global.worker.resources | indent 12 }}

{{- with .Values.global.worker.hostPathMounts }}
{{- if .}}
          volumeMounts:
{{- range . }}
            - name: {{ .name }}
              mountPath: {{ .dest }}
              mountPropagation: HostToContainer
{{- end }}
      volumes:
{{- range . }}
        - name: {{ .name }}
          hostPath:
            path: {{ .src }}
{{- end }}
{{- end }}
{{- end }}

{{- with .Values.global.worker.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.global.worker.tolerations | default .Values.global.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}

{{- end }}
