{{- $componentName := "worker" -}}
---
{{- if .Values.global.imageOverrides.nodejssdk }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipes.fullname" (dict "suffix" $componentName "root" .) }}
  labels:
{{ include "pipes.labels" . | indent 4 }}
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 6 }}
  template:
    metadata:
      labels:
        timestamp: "{{ now | date "20060102150405" }}"
{{ include "pipes.selectorLabels" (dict "suffix" $componentName "root" .) | indent 8 }}
    spec:
{{ include "pipes.imagePullSecrets" . | indent 6 }}
      containers:
        - name: nodejs
          image: {{ include "pipes.imageFullname" (dict "image" "nodejssdk" "root" .) }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
          env:
{{- range $name, $def := .Values.global.nodejsSdk.extraEnv }}
            - name: {{ $name }}
              {{- $def | toYaml | nindent 14}}
{{- end }}
            - name: BACKEND_URL
              value: "{{ .Values.global.backend_url }}"
            - name: STARTING_POINT_URL
              value: "{{ .Values.global.starting_point_url }}"
            - name: CRYPT_SECRET
              valueFrom:
                secretKeyRef:
                  key: crypt_secret
                  name: {{ include "pipes.fullname" (dict "suffix" "secrets" "root" .) }}
            - name: ORCHESTY_API_KEY
              valueFrom:
                secretKeyRef:
                    key: orchesty_api_key
                    name: {{ include "pipes.fullname" (dict "suffix" "secrets" "root" .) }}
{{- if .Values.global.nodejsSdk.worker_api_url }}
            - name: WORKER_API_HOST
              value: {{ .Values.global.nodejsSdk.worker_api_url }}
{{- else }}
            - name: WORKER_API_HOST
              value: http://{{ include "pipes.selectorLabels" (dict "suffix" "worker-api" "root" .) }}
{{- end }}
          resources:
{{ toYaml .Values.global.worker.resources | indent 12 }}

{{- with .Values.global.worker.hostPathMounts }}
{{- if .}}
          volumeMounts:
{{- range . }}
            - name: {{ .name }}
              mountPath: {{ .dest }}
              mountPropagation: HostToContainer
{{- end }}
      volumes:
{{- range . }}
        - name: {{ .name }}
          hostPath:
            path: {{ .src }}
{{- end }}
{{- end }}
{{- end }}

{{- with .Values.global.worker.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.global.worker.tolerations | default .Values.global.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}

{{- end }}
