apiVersion: v2
name: orchesty
description: Orchesty is a platform + framework for systems integration and process orchestration. See https://orchesty.io
type: application
version: 2.1.14
appVersion: 2.1.1

# Add dependencies
dependencies:
  - name: valkey
    version: 0.7.7
    repository: https://valkey-io.github.io/valkey-helm/
    condition: valkey.enabled
  
  - name: grafana
    version: 10.3.0
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  
  - name: loki
    version: 6.46.0
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled
  
  - name: alloy
    version: 1.5.0
    repository: https://grafana.github.io/helm-charts
    condition: alloy.enabled