---
apiVersion: v1
kind: Secret
metadata:
  name: orchesty
stringData:
  license: ""
  backend_jwt_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  backend_x_auth_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

  crypt_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  orchesty_api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

  email_dsn: "gmail://xxxx@yyyyyy.zz:aaaaaaaaaaaaa@localhost"

  # please keep /<database> the same as XY_DB=<database>
  mongodb_dsn: mongodb://pipes-mongodb/pipes?authSource=admin
  mongodb_db: pipes
  metrics_dsn: mongodb://pipes-mongodb/metrics?authSource=admin
  metrics_db: metrics

  rabbitmq_dsn: amqp://guest:guest@pipes-rabbitmq:5672/
  rabbitmq_host: pipes-rabbitmq
  rabbitmq_port: "5672"
  rabbitmq_vhost: ""
  rabbitmq_user: guest
  rabbitmq_password: guest

  applinth_jwe_private_key: |
    -----BEGIN EC PRIVATE KEY-----
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    -----END EC PRIVATE KEY-----