---
apiVersion: v1
kind: Secret
metadata:
  name: orchesty-secrets
stringData:
  backend_jwt_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

  crypt_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  orchesty_api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

  # please keep /<database> the same as XY_DB=<database>
  mongodb_dsn: mongodb://pipes-mongodb/pipes?authSource=admin
  mongodb_db: pipes
  metrics_dsn: mongodb://pipes-mongodb/metrics?authSource=admin
  metrics_db: metrics

  rabbitmq_dsn: amqp://guest:guest@pipes-rabbitmq:5672/

  applinth_jwe_private_key: |
    -----BEGIN EC PRIVATE KEY-----
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    -----END EC PRIVATE KEY-----
